---
abstract: 'Module::Starter for RT extensions'
author:
  - 'sunnavy <sunnavy@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Starter-Plugin-RTx
requires:
  Module::Install::RTx: 0
  Module::Starter: 0
resources:
  repository: git://github.com/sunnavy/module-starter-plugin-rtx.git
version: 0.02
